#include<iostream>
using namespace std;
class Calculator
{
    int a,b;
public:
    void getData()
    {
        cout<<"Enter two numbers: ";
        cin>>a>>b;
    }
    void calculate()
    {
        cout<<"Addition = "<<a+b<<endl;
        cout<<"Subtraction = "<<a-b<<endl;
        cout<<"Multiplication = "<<a*b<<endl;
        cout<<"Division = "<<a/b<<endl;
    }
};
int main()
{
    Calculator c;
    c.getData();
    c.calculate();
}